app: # 基本配置信息
  env: local # 环境
  port: 8889 # 服务监听端口
  app_name: base_showcase # 应用名称
  app_url: http://localhost # 应用域名
  db_type: mysql # 使用的数据库

zap: # 日志配置
  level: info # 日志级别
  prefix: '[east_white_common_admin/server]' # 日志前缀
  format: console # 输出
  director: log # 日志存放的文件
  encode_level: LowercaseColorLevelEncoder # 编码级别
  stacktrace_key: stacktrace # 栈名
  max_age: 0 # 日志留存时间
  show_line: true # 显示行
  log_in_console: true # 输出控制台

mysql: # MySQL 配置
  host: 127.0.41.15 # 服务器地址
  port: "3308" # 端口
  config: charset=utf8mb4&parseTime=True&loc=Local # 其他配置
  db_name: test_db # 数据库名称
  username: root # 数据库用户名
  password: "root" # 数据库密码
  prefix: "t_" # 全局表前缀，单独定义 TableName 则不生效
  singular: false # 是否开启全局禁用复数，true表示不开启
  engine: "" # 引擎，默认InnoDB
  max_idle_conns: 10 # 最大空闲连接数
  max_open_conns: 100 # 最大连接数
  log_mode: error # 日志级别
  log_zap: false # 是否通过zap写日志文件




